# Generated by Django 4.2.3 on 2023-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.TextField(verbose_name='response')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
